###
POST http://localhost:5000/admin/auth HTTP/1.1
Content-Type: application/json

# {
#     "username": "teacher_john_doe",
#     "password": "SecurePassword123!"
# }

{
  "username": "dev",
  "password": "admin"
}

###
POST http://localhost:5000/admin/create-student HTTP/1.1
Content-Type: application/json
administrator-token: eyJhbGciOiJIUzI1NiJ9.ZGV2.nt3RbLmN5fz-qdkMuhpl9SpktlfaxwgJJkCdNbdAp9g

{
  "username": "student_john_doe2",
  "password": "SecurePassword123!",
  "role": "teacher",
  "firstname": "Johnathan",
  "lastname": "Doe again",
  "address": "456 Oak Street",
  "grade": "11",
  "dob": "2002-03-20"
}

###
POST http://localhost:5000/admin/update-user/data HTTP/1.1
Content-Type: application/json
dev-token: eyJhbGciOiJIUzI1NiJ9.ZGV2.nt3RbLmN5fz-qdkMuhpl9SpktlfaxwgJJkCdNbdAp9g

{
  "key": "personal_infos", "value": "Second Testing", "user_id": "6554eeb8217c4ad5c40761ec", "role": "student"
}

### 

POST http://localhost:5000/admin/create-content HTTP/1.1
Content-Type: application/json
dev-token: eyJhbGciOiJIUzI1NiJ9.ZGV2.nt3RbLmN5fz-qdkMuhpl9SpktlfaxwgJJkCdNbdAp9g

{
  "type": "news",
  "title": " Programming",
  "description": "A beginner-friendly guide to programming concepts.",
  "link": "https://example.com/intro-to-programming"
}

###
POST http://localhost:5000/admin/update-calender HTTP/1.1
Content-Type: application/json
teacher-token: eyJhbGciOiJIUzI1NiJ9.dGVhY2hlcl9qb2huX2RvZQ.TsbsPXQBQrAGTUsr5_J3QmjUHrSE3BKVt7YTaJWR2BU
{
  "id": "655567c82b145221351a361b",
  "key": "descriptionddd",
  "value": "Testing the description change",
  "date": "2023-11-15",
  "type": "academic event"
}

